def build(bld):
    def set_properties(obj):
        obj.use = obj.ns3_module_dependencies
        obj.install_path = None

    all_modules = [mod[len("ns3-"):] for mod in bld.env['NS3_ENABLED_MODULES']]
    obj = bld.create_ns3_program('multipath_routing', all_modules)
    obj.source = ['multipath-routing.cc',
                  'src/flow.cc',
                  'src/terminal.cc',
                  'src/sdn-switch.cc',
                  'src/switch-base.cc',
                  'src/ppfs-switch.cc',
                  'src/mptcp-header.cc',
                  'src/receiver-app.cc',
                  'src/custom-device.cc',
                  'src/routing-helper.cc',
                  'src/result-manager.cc',
                  'src/transmitter-app.cc',
                  'src/application-base.cc',
                  'src/topology-builder.cc',
                  'src/application-helper.cc',
                  'src/single-path-receiver.cc',
                  'src/single-path-transmitter.cc',
                  'src/random-generator-manager.cc']

    obj.env.append_value('LIB', ['tinyxml2'])  # Adding the tinyxml2 library
    set_properties(obj)
