## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import os

home_folder = os.path.expanduser('~')
lemon_include = '-I' + home_folder + '/libraries/lemon/include'
lemon_library = '-L' + home_folder + '/libraries/lemon/lib'

def build(bld):
    def set_properties(obj):
        obj.use = obj.ns3_module_dependencies
        obj.install_path = None

    all_modules = [mod[len("ns3-"):] for mod in bld.env['NS3_ENABLED_MODULES']]
    obj = bld.create_ns3_program('ospf-network', all_modules)
    obj.source = ['ospf-network.cc',
                  '../multipath-mcf/custom-bridge/custom-bridge-net-device.cc',
                  '../multipath-mcf/custom-bridge/custom-bridge-helper.cc',
                  '../multipath-mcf/custom-bridge/custom-bridge-channel.cc',
                  '../multipath-mcf/classes/routing-table.cc',
                  '../multipath-mcf/classes/graph-utilities.cc',
                  '../multipath-mcf/classes/commodity-utilities.cc',
                  '../multipath-mcf/classes/commodity-properties.cc',
                  '../multipath-mcf/classes/simulation-configurator.cc',
                  '../multipath-mcf/classes/xml-file-handler.cc',
                  '../multipath-mcf/classes/log-manager.cc',
                  '../multipath-mcf/classes/result-manager.cc']
    obj.env.append_value('CXXFLAGS', lemon_include)
    obj.env.append_value('LINKFLAGS', [lemon_library])
    obj.env.append_value('LIB', ['emon', 'glpk', 'tinyxml2'])                  
    set_properties(obj)
